apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster-recent
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    foo_user:
  
  #databases: name->owner
  databases:
    foo: zalando
  postgresql:
    version: "10"
  dockerImage: registry.opensource.zalan.do/acid/spilotest-10:improve-support-for-namespaces-v1
